version: 2
jobs:
  test:
    docker:
      - image: grampajoe/minicomi-ci
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            pip install -r requirements.txt
            pip install -r requirements-test.txt
      - run:
          name: Run tests
          command: CI=true make test


workflows:
  version: 2
  test:
    jobs:
      - test
