version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.3
    steps:
      - checkout
      - run:
          name: Install geckodriver
          command: |
            curl -L https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz > geckodriver.tar.gz
            tar -zxvf geckodriver.tar.gz
            sudo chmod +x geckodriver
            sudo mv geckodriver /usr/bin
      - run:
          name: Create virtualenv
          command: python -m venv ~/env
      - run:
          name: Install requirements
          command: |
            pip install -r requirements.txt
            pip install -r requirements-test.txt


workflows:
  version: 2
  test:
    jobs:
      - test
